services:
  - type: web
    name: translatica
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8000
      - key: DEVICE
        value: cpu
    healthCheckPath: /health