services:
  - type: web
    name: translatica
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
      - key: DEVICE
        value: cpu
    healthCheckPath: /health